const activities = {
  "🎬 Movie": {
    "🎥 Single Movie": {
      Action: [
        "John Wick: Chapter 4",
        "Mad Max: Fury Road",
        "The Raid 2",
        "Other",
      ],
      Comedy: ["Game Night", "21 Jump Street", "The Nice Guys", "Other"],
      Horror: ["Talk to Me", "Hereditary", "Smile", "Other"],
      Romance: [
        "La La Land",
        "Anyone But You",
        "10 Things I Hate About You",
        "Other",
      ],
      Thriller: ["Prisoners", "Gone Girl", "Nightcrawler", "Other"],
      "Sci-Fi": ["Interstellar", "The Martian", "Edge of Tomorrow", "Other"],
      Fantasy: [
        "Dungeons & Dragons: Honor Among Thieves",
        "Fantastic Beasts and Where to Find Them",
        "The Green Knight",
        "Other",
      ],
      Animation: [
        "Spider-Man: Into the Spider-Verse",
        "The Super Mario Bros. Movie",
        "How to Train Your Dragon",
        "Other",
      ],
      Mystery: [
        "Knives Out",
        "Glass Onion",
        "Murder on the Orient Express",
        "Other",
      ],
    },
    "🎞 Movie Marathon": [
      "Marvel Cinematic Universe",
      "Harry Potter",
      "The Lord of the Rings + The Hobbit",
      "Pirates of the Caribbean",
      "Mission: Impossible",
      "John Wick",
      "The Hunger Games",
      "Scream",
      "The Conjuring Universe",
      "Fast & Furious",
      "Other",
    ],
  },

  "📺 Binge Watch Series": {
    Comedy: [
      "Brooklyn Nine-Nine",
      "The Good Place",
      "Ted Lasso",
      "Derry Girls",
      "Jury Duty",
      "Other",
    ],
    Sitcom: [
      "Friends",
      "How I Met Your Mother",
      "Modern Family",
      "The Office (US)",
      "New Girl",
      "Other",
    ],
    Crime: [
      "Breaking Bad",
      "Narcos",
      "Mindhunter",
      "True Detective",
      "Ozark",
      "Other",
    ],
    Drama: ["Succession", "This Is Us", "The Crown", "Shōgun", "Beef", "Other"],
    Fantasy: [
      "Game of Thrones",
      "House of the Dragon",
      "Shadow and Bone",
      "The Witcher",
      "The Sandman",
      "Other",
    ],
    Horror: [
      "The Haunting of Hill House",
      "From",
      "Midnight Mass",
      "The Fall of the House of Usher",
      "Marianne",
      "Other",
    ],
    Romance: [
      "Bridgerton",
      "One Day",
      "Nobody Wants This",
      "Heartstopper",
      "Normal People",
      "Other",
    ],
    "Sci-Fi": [
      "Dark",
      "Severance",
      "Silo",
      "The Expanse",
      "Black Mirror",
      "Other",
    ],
    Anime: [
      "Attack on Titan",
      "Demon Slayer",
      "Jujutsu Kaisen",
      "Frieren: Beyond Journey's End",
      "Death Note",
      "Other",
    ],
    Documentary: [
      "Planet Earth II",
      "Our Planet",
      "Formula 1: Drive to Survive",
      "Welcome to Wrexham",
      "The Last Dance",
      "Other",
    ],
    Reality: [
      "The Amazing Race",
      "Survivor",
      "Love Is Blind",
      "The Circle",
      "Physical: 100",
      "Other",
    ],
  },

  "🍳 Cook/Bake Together": {
    Cook: {
      Italian: ["Chicken Alfredo", "Spaghetti Carbonara", "Lasagna", "Other"],
      Indian: [
        "Butter Chicken",
        "Paneer Butter Masala",
        "Chicken Biryani",
        "Other",
      ],
      Mexican: ["Beef Tacos", "Chicken Quesadillas", "Burritos", "Other"],
      Chinese: ["Fried Rice", "Sweet & Sour Chicken", "Chow Mein", "Other"],
      Burgers: [
        "Classic Cheeseburger",
        "Crispy Chicken Burger",
        "Smash Burger",
        "Other",
      ],
      Pasta: [
        "Creamy Garlic Parmesan Pasta",
        "Bolognese",
        "Pesto Pasta",
        "Other",
      ],
      Pizza: ["Margherita", "Pepperoni", "BBQ Chicken Pizza", "Other"],
      Healthy: [
        "Grilled Salmon Bowl",
        "Chicken Caesar Salad",
        "Teriyaki Chicken Rice Bowl",
        "Other",
      ],
    },
    Bake: {
      Cookies: ["Chocolate Chip", "Red Velvet", "Double Chocolate", "Other"],
      Brownies: [
        "Fudge Brownies",
        "Oreo Brownies",
        "Salted Caramel Brownies",
        "Other",
      ],
      Cake: ["Chocolate Cake", "Red Velvet Cake", "Lemon Cake", "Other"],
      Cupcakes: ["Vanilla", "Chocolate", "Cookies & Cream", "Other"],
      Bread: ["Garlic Bread", "Focaccia", "Cinnamon Bread", "Other"],
      Muffins: ["Blueberry", "Chocolate Chip", "Banana Nut", "Other"],
      Cheesecake: ["New York", "Oreo", "Strawberry", "Other"],
      Pastries: ["Croissants", "Apple Turnovers", "Danish Pastries", "Other"],
    },
  },

  "🎨 Painting/Colouring": [
    "Canvas Painting",
    "Watercolour",
    "Acrylic",
    "Colouring Pages",
    "Digital Art",
    "Pixel Art",
    "Mandalas",
    "Paint by Numbers",
  ],

  "🎮 Game Night": {
    "Co-op": [
      "Minecraft",
      "Stardew Valley",
      "Portal 2",
      "Don't Starve Together",
      "It Takes Two",
      "Other",
    ],
    Puzzle: [
      "We Were Here",
      "Tick Tock: A Tale for Two",
      "Escape Simulator",
      "Keep Talking and Nobody Explodes",
      "The Past Within",
      "Other",
    ],
    Party: [
      "Among Us",
      "UNO! Mobile",
      "Gartic Phone",
      "Jackbox Party Pack",
      "Heads Up!",
      "Other",
    ],
    Competitive: [
      "Brawlhalla",
      "Rocket League",
      "Chess.com",
      "8 Ball Pool",
      "Clash Royale",
      "Other",
    ],
    Relaxing: [
      "Animal Crossing: Pocket Camp Complete",
      "Stardew Valley",
      "Minecraft",
      "Terraria",
      "Sky: Children of the Light",
      "Other",
    ],
  },

  "📚 Read a Book": {
    Romance: [
      "The Seven Husbands of Evelyn Hugo",
      "Book Lovers",
      "Beach Read",
      "Other",
    ],
    Fantasy: [
      "Fourth Wing",
      "The Name of the Wind",
      "A Court of Thorns and Roses",
      "Other",
    ],
    Mystery: [
      "The Silent Patient",
      "The Girl with the Dragon Tattoo",
      "The Thursday Murder Club",
      "Other",
    ],
    Thriller: [
      "Gone Girl",
      "The Housemaid",
      "The Woman in the Window",
      "Other",
    ],
    Horror: ["The Shining", "Mexican Gothic", "Bird Box", "Other"],
    "Sci-Fi": ["Project Hail Mary", "The Martian", "Dune", "Other"],
    "Young Adult": [
      "The Hunger Games",
      "Six of Crows",
      "The Inheritance Games",
      "Other",
    ],
    Classics: [
      "Pride and Prejudice",
      "The Great Gatsby",
      "To Kill a Mockingbird",
      "Other",
    ],
    Biography: ["I'm Glad My Mom Died", "Educated", "Becoming", "Other"],
    "Self-Help": [
      "Atomic Habits",
      "The Psychology of Money",
      "The Subtle Art of Not Giving a F*ck",
      "Other",
    ],
  },
};
